##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.1.0] date: [Fri Jun 14 13:21:07 CDT 2019] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = lorawanFeather


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Src/main.c \
Src/usb_device.c \
Src/usbd_conf.c \
Src/usbd_desc.c \
Src/usbd_cdc_if.c \
Src/stm32l1xx_it.c \
Src/stm32l1xx_hal_msp.c \
Src/bsp.c \
Src/debug.c \
Src/hw_gpio.c \
Src/hw_rtc.c \
Src/hw_spi.c \
Src/stm32l1xx_hw.c \
Src/stm32l1xx_nucleo.c \
Src/sx1276.c \
Src/sx1276mb1mas.c \
Src/system_stm32l1xx.c \
Src/vcom.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_adc.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_adc_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_cortex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_dma.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash_ramfunc.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_flash.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_gpio.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_i2c.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pcd.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pcd_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_pwr_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rcc_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rtc.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_rtc_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_spi.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_spi_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_tim_ex.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_uart.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal_usart.c \
Drivers/STM32L1xx_HAL_Driver/Src/stm32l1xx_hal.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_core.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ctlreq.c \
Middlewares/ST/STM32_USB_Device_Library/Core/Src/usbd_ioreq.c \
Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Src/usbd_cdc.c \
Middlewares/Third_Party/LoRaWAN/Core/lora.c \
Middlewares/Third_Party/LoRaWAN/Core/lora-test.c \
Middlewares/Third_Party/LoRaWAN/Crypto/aes.c \
Middlewares/Third_Party/LoRaWAN/Crypto/cmac.c \
Middlewares/Third_Party/LoRaWAN/Crypto/soft-se.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMac.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacAdr.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacClassB.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacCommands.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacConfirmQueue.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacCrypto.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacFCntHandler.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacParser.c \
Middlewares/Third_Party/LoRaWAN/Mac/LoRaMacSerializer.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/Region.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionAS923.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionAU915.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCN470.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCN779.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionCommon.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionEU433.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionEU868.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionIN865.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionKR920.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionRU864.c \
Middlewares/Third_Party/LoRaWAN/Mac/region/RegionUS915.c \
Middlewares/Third_Party/LoRaWAN/Utilities/low_power_manager.c \
Middlewares/Third_Party/LoRaWAN/Utilities/queue.c \
Middlewares/Third_Party/LoRaWAN/Utilities/systime.c \
Middlewares/Third_Party/LoRaWAN/Utilities/timeServer.c \
Middlewares/Third_Party/LoRaWAN/Utilities/trace.c \
Middlewares/Third_Party/LoRaWAN/Utilities/utilities.c

# ASM sources
ASM_SOURCES =  \
startup_stm32l152xe.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m3

# fpu
# NONE for Cortex-M0/M0+/M3

# float-abi


# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32L152xE \
-DUSE_STM32L1XX_NUCLEO \
-DREGION_US915 

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-IInc \
-IDrivers/STM32L1xx_HAL_Driver/Inc \
-IDrivers/STM32L1xx_HAL_Driver/Inc/Legacy \
-IMiddlewares/ST/STM32_USB_Device_Library/Core/Inc \
-IMiddlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc \
-IDrivers/CMSIS/Device/ST/STM32L1xx/Include \
-IDrivers/CMSIS/Include \
-IMiddlewares/Third_Party/LoRaWAN/Core \
-IMiddlewares/Third_Party/LoRaWAN/Crypto \
-IMiddlewares/Third_Party/LoRaWAN/Mac \
-IMiddlewares/Third_Party/LoRaWAN/Mac/region \
-IMiddlewares/Third_Party/LoRaWAN/Phy \
-IMiddlewares/Third_Party/LoRaWAN/Utilities \
-ILib/uart_printf

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32L152RETx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	rm -R $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
